#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-cf"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "2206f767661647f4a18a075f3bfbf556" }
]
